export const ERR_KEY_NOT_FOUND = "KEY_NOT_FOUND";
export const ERR_DUPLICATE_KEY = "DUPLICATE_KEY";
export const ERR_KEY_CREATE_FAILED = "KEY_CREATE_FAILED";
export const ERR_KEY_UPDATE_FAILED = "KEY_UPDATE_FAILED";
export const ERR_KEY_VALIDATION = "KEY_VALIDATION";
export const ERR_KEY_ALREADY_ROTATED = "KEY_ALREADY_ROTATED";
export const ERR_ROTATION_FAILED = "ROTATION_FAILED";

export const ERR_WORKSPACE_NOT_FOUND = "WORKSPACE_NOT_FOUND";
export const ERR_DUPLICATE_WORKSPACE = "DUPLICATE_WORKSPACE";
export const ERR_WORKSPACE_CREATE_FAILED = "WORKSPACE_CREATE_FAILED";
export const ERR_WORKSPACE_VALIDATION = "WORKSPACE_VALIDATION";

export const ERR_RATE_LIMIT_INVALID = "RATE_LIMIT_INVALID";
export const ERR_KEY_EXPIRED = "KEY_EXPIRED";

export const ERR_INTERNAL_ERROR = "INTERNAL_ERROR";
export const ERR_REDIS = "REDIS_ERROR";
